name: swift_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  agora_rtc_engine: ^6.1.0
  auto_route: ^5.0.1
  cached_network_image: ^3.2.1
  chat_bubbles: ^1.3.1
  iconsax: ^0.0.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  timeago: ^3.3.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/